"""Package reviewed, hash-verified original Sternenepoche artwork for both clients.
No model download or regeneration; production masters remain in content/.
"""
from pathlib import Path
import json, hashlib, re
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
def build():
    catalog=json.loads((ROOT/'content/catalog.json').read_text(encoding='utf-8-sig'))
    output=ROOT/'web-client/assets'; output.mkdir(exist_ok=True)
    images={}; embeds=[]; missing=[]
    for a in catalog['assets']:
        src=ROOT/'content'/a['file']; proof=src.with_suffix('.provenance.json')
        if not proof.exists() or not src.exists(): missing.append(a['id']); continue
        p=json.loads(proof.read_text(encoding='utf-8-sig'))
        if not p.get('reviewed') or p.get('sha256')!=hashlib.sha256(src.read_bytes()).hexdigest():
            missing.append(a['id']); continue
        name=a['id']+'.webp'; dst=output/name
        if '--manifest-only' not in __import__('sys').argv or not dst.exists():
            with Image.open(src) as im:
                im=im.convert('RGB'); im.thumbnail((1024,768) if a['category']=='backgrounds' else (480,480))
                im.save(dst,'WEBP',quality=83,method=6)
        images['|'.join([a['category'],a['key'],a.get('faction') or ''])]={'url':'assets/'+name+'?v='+p['sha256'][:12],'label':a['label']}
        embeds.append(f'        "/assets/{name}" => Some((include_bytes!("../../../web-client/assets/{name}").as_slice(), "image/webp")),')
    name_source=(ROOT/'crates/spieler/src/ansicht/namen.rs').read_text(encoding='utf-8').split('pub fn gut(')[0]
    names=dict(re.findall(r'"([^"\n]+)" => "([^"\n]+)"',name_source))
    (ROOT/'web-client/art.js').write_text('window.STERNEN_ART='+json.dumps({'images':images,'names':names},ensure_ascii=False,separators=(',',':'))+';\n',encoding='utf-8')
    (ROOT/'crates/server/src/web_assets.rs').write_text('// Generated by tools/build_web_art.py. Explicit public files only.\npub fn get(path:&str)->Option<(&\'static [u8],&\'static str)>{\n    match path {\n'+'\n'.join(embeds)+'\n        _=>None,\n    }\n}\n',encoding='utf-8')
    print(json.dumps({'packaged':len(images),'missing_or_unreviewed':missing,'bytes':sum(p.stat().st_size for p in output.glob('*.webp'))}))
if __name__=='__main__':build()
