'use strict';
// Credentials and successful probes deliberately live only in this tab's memory.
window.AgentTeam=(()=>{
 const roles=['stratege','verwalter','feldherr','diplomat'], keys=new Map(), probes=new Map(), catalogs=new Map();
 let data=null, revision=0, journal=[], owner='', dirty=false, syncing=false, testing=false, testAbort=null, busy=false;
 const uid=()=>crypto.randomUUID(), clone=x=>JSON.parse(JSON.stringify(x));
 const duties={stratege:'Formuliere langfristige Ziele und konkrete nächste Schritte. Koordiniere die anderen Rollen, prüfe Versorgung vor Expansion.',verwalter:'Sichere Energie, Nahrung, Lager und Wirtschaft. Stimme Ressourcenbedarf mit dem Feldherrn und Handelsbedarf mit dem Diplomaten ab.',feldherr:'Schütze das Reich und plane Flotten vorsichtig. Fordere fehlende Ressourcen beim Verwalter an. Beachte Treibstoff und Rückkehr.',diplomat:'Pflege Kontakte, beantworte offene Briefe und koordiniere Handel. Prüfe Angebote und Zusagen mit dem Verwalter; behaupte nie einen unbestätigten Abschluss.'};
 function defaults(){return {models:[],roles:Object.fromEntries(roles.map(r=>[r,{model:'',soul:'Du bist ein zuverlässiges Teammitglied. Sprich Kollegen mit ihrem Namen an, unterscheide Fakten, Pläne und Vermutungen und halte Zusagen auf der Pinwand fest.',instructions:duties[r]}])),boards:[{id:uid(),title:'Gemeinsamer Plan',world_id:world?.world_id||'',notes:[]}],delay:60,limit:100,cost_limit:1};}
 const state=()=>data||(data=defaults());
 function localURL(value){let u;try{u=new URL(value);}catch{throw Error('Ollama-Adresse ungültig. Beispiel: http://127.0.0.1:11434');}if(!['127.0.0.1','localhost','[::1]'].includes(u.hostname)||!['http:','https:'].includes(u.protocol)||u.username||u.password||u.search||u.hash||u.pathname!=='/')throw Error('Trage nur den lokalen API-Ursprung ein, zum Beispiel http://127.0.0.1:11434, ohne /api/chat oder /api/tags.');return u.origin;}
 function config(m){if(!m?.model.trim())throw Error('Für jedes verwendete Teammitglied ein konkretes Modell auswählen.');const c={...m,key:keys.get(m.id)||''};if(m.provider==='ollama')c.url=localURL(m.url);else if(!c.key)throw Error(m.name+': OpenRouter-Schlüssel fehlt. Er wird nach Neuladen erneut benötigt.');return c;}
 function fingerprint(m){return JSON.stringify([m.provider,m.url,m.model,keys.get(m.id)||'']);}
 function checked(m){return probes.get(m.id)?.fingerprint===fingerprint(m)&&probes.get(m.id)?.ok;}
 function status(t,error=false){const e=$('team-feedback');if(e){e.textContent=t;e.classList.toggle('error',error);} }
 function changed(){dirty=true;status('Ungespeicherte Änderungen. „Team & Pinwände speichern“ übernimmt sie ins Konto.');}
 function modelOptions(value){return '<option value="">Mensch · keine Agentfreigabe</option>'+state().models.map(m=>`<option value="${esc(m.id)}" ${m.id===value?'selected':''}>${esc(m.name)} · ${esc(m.model||'Modell fehlt')}</option>`).join('');}
 function render(){
  const s=state(),root=$('team-workbench');if(!root)return;
  root.innerHTML=`<div class="team-heading"><div><span class="team-eyebrow">DEINE KOMMANDOCREW</span><h2>Vier Rollen. Dein Team.</h2><p>Bis zu vier benannte Modelle, lokal und über OpenRouter gemischt. Ein Modell kann mehrere Rollen übernehmen.</p></div><span class="team-chip">Ollama · automatisch nacheinander</span></div>
  <div class="team-steps"><span>1 · Modelle verbinden & testen</span><span>2 · Rollen zuordnen</span><span>3 · Speichern & starten</span></div>
  <div class="row"><button type="button" data-team="add-model" ${s.models.length>=4?'disabled':''}>＋ Modell hinzufügen</button><button type="button" data-team="test-all">Alle Modelle testen</button><button type="button" data-team="cancel-test" ${!testing?'hidden':''}>Test abbrechen</button><a href="agenten-hilfe.html" target="_blank" rel="noopener">Schritt-für-Schritt-Anleitung ↗</a></div>
  <p class="muted">Tests funktionieren auch ohne Spielplatz und führen keine Spielaktionen aus. OpenRouter-Tests sind echte, möglicherweise kostenpflichtige Anfragen.</p>
  <div class="team-models">${s.models.map((m,i)=>`<article class="team-model" data-model-id="${esc(m.id)}"><div class="row"><h3><span class="team-number">0${i+1}</span> ${esc(m.name)}</h3><button type="button" class="secondary" data-team="remove-model" data-id="${esc(m.id)}" aria-label="${esc(m.name)} entfernen">Entfernen</button></div>
   <label>Name im Team<input data-model="name" maxlength="40" value="${esc(m.name)}" placeholder="z. B. Nova"></label><label>Anbieter<select data-model="provider"><option value="ollama" ${m.provider==='ollama'?'selected':''}>Ollama · mein Rechner</option><option value="openrouter" ${m.provider==='openrouter'?'selected':''}>OpenRouter</option></select></label>
   ${m.provider==='ollama'?`<label>Lokaler Ollama-API-Punkt<input data-model="url" type="url" value="${esc(m.url)}" placeholder="http://127.0.0.1:11434"></label>`:`<label>OpenRouter API-Key<input data-key="${esc(m.id)}" type="password" autocomplete="new-password" placeholder="Nur in diesem Tab · niemals auf dem Spielserver"></label>`}
   <div class="row"><button type="button" data-team="list-models" data-id="${esc(m.id)}">Modelle laden</button><small>${m.provider==='ollama'?'Nur bereits installierte Modelle':'Modellkatalog von OpenRouter'}</small></div>
   <label>Exakte Modell-ID<input data-model="model" list="models-${esc(m.id)}" maxlength="160" value="${esc(m.model)}" placeholder="${m.provider==='ollama'?'Name:Tag aus der Liste':'anbieter/modell-id'}"></label><datalist id="models-${esc(m.id)}">${(catalogs.get(m.id)||[]).map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('')}</datalist>
   ${(catalogs.get(m.id)||[]).length?`<label>Aus gefundener Liste wählen<select data-catalog="${esc(m.id)}"><option value="">Modell auswählen …</option>${catalogs.get(m.id).map(x=>`<option value="${esc(x.id)}" ${x.id===m.model?'selected':''}>${esc(x.name)}</option>`).join('')}</select>`:''}
   <button type="button" data-team="test" data-id="${esc(m.id)}">Verbindung & JSON-Antwort testen</button><button type="button" class="secondary" data-team="rehearse" data-id="${esc(m.id)}">Spielentscheidung proben · ohne Befehle</button><p class="team-probe ${checked(m)?'good':''}" role="status" data-probe-result="${esc(m.id)}">${esc(probes.get(m.id)?.message||'Noch nicht getestet')}</p></article>`).join('')||'<p class="empty">Füge dein erstes Modell hinzu. Ein einziges Modell genügt für alle vier Rollen.</p>'}</div>
  <details class="team-origins"><summary>Ollama ist gestartet, aber der Browser erreicht es nicht?</summary><p>Diese Website hat den Ursprung <code>${esc(location.origin)}</code>. Erlaube genau diesen Ursprung in <code>OLLAMA_ORIGINS</code>, beende Ollama vollständig und starte es neu. Erlaube auch den lokalen Netzwerkzugriff, falls dein Browser danach fragt.</p><p>Windows PowerShell (andere benötigte Ursprünge gegebenenfalls durch Komma ergänzen):</p><pre>[Environment]::SetEnvironmentVariable('OLLAMA_ORIGINS', '${esc(location.origin.replaceAll("'","''"))}', 'User')</pre><p>Die Modelladresse ist der API-Punkt auf dem Gerät, auf dem dieser Browser läuft. Ein Handy erreicht über 127.0.0.1 nicht deinen PC. Keine Portfreigabe ins Internet erforderlich. <a href="agenten-hilfe.html#fehler" target="_blank" rel="noopener">Fehlerhilfe öffnen</a>.</p></details>
  <h3>Rollen & Persönlichkeit</h3><p>${session?.mode==='agent'?'Agentenspiel: Alle vier Rollen müssen besetzt sein. Beim Start beraten die Modelle über ihre Aufgaben; alle sehen die Vorschläge ihrer Kollegen.':'Mensch / Mischbetrieb: Du bestimmst die Zuordnung. „Mensch“ lässt die jeweilige Rolle bei dir.'} Die Zuordnung und Texte lassen sich jederzeit ändern. Speichern stoppt ein laufendes Team vor der Übernahme; danach startest du es erneut.</p>
  <div class="team-roles">${roles.map(r=>`<details data-role-id="${r}"><summary>${esc(label(r))} · ${esc(s.models.find(m=>m.id===s.roles[r].model)?.name||'Mensch')}</summary><label>Zugeordnetes Modell<select data-role="model">${modelOptions(s.roles[r].model)}</select></label><label>soul.md · Persönlichkeit & Umgang<textarea data-role="soul" maxlength="2000" rows="4">${esc(s.roles[r].soul)}</textarea></label><label>rollen.md · Aufgaben & Arbeitsweise<textarea data-role="instructions" maxlength="3000" rows="5">${esc(s.roles[r].instructions)}</textarea></label><div class="row"><button type="button" data-team="export-role" data-id="${r}" data-file="soul">soul.md herunterladen</button><button type="button" data-team="export-role" data-id="${r}" data-file="instructions">rollen.md herunterladen</button><label>Markdown importieren<input type="file" accept=".md,text/markdown,text/plain" data-import-role="${r}"></label><select aria-label="Importziel für ${r}" data-import-target="${r}"><option value="soul">soul.md</option><option value="instructions">rollen.md</option></select></div></details>`).join('')}</div>
  <div class="team-limits"><label>Aufrufe je Start (inklusive Teamberatung)<input data-limit="limit" type="number" min="1" max="10000" value="${s.limit}"></label><label>Gemeldetes Kostenlimit in USD<input data-limit="cost_limit" type="number" min="0" step="0.01" value="${s.cost_limit}"></label><label>Rundenabstand in Sekunden<input data-limit="delay" type="number" min="15" max="3600" value="${s.delay}"></label></div>
  <p class="muted">Jede Modellantwort verbraucht einen Aufruf. Das Kostenlimit reagiert auf gemeldete Kosten und kann um die letzte Anfrage überschritten werden. Setze das harte Ausgabenlimit zusätzlich am OpenRouter-Schlüssel. 0 deaktiviert nur das gemeldete Kostenlimit.</p>
  <div class="row"><button type="button" data-team="save">Team & Pinwände speichern</button><button type="button" data-team="reload">Gespeicherten Stand laden</button><button type="button" data-team="start">Team starten / fortsetzen</button><button type="button" class="danger" data-team="stop">Team stoppen</button></div><p id="team-feedback" role="status">${session?'Konfiguration im Konto · Schlüssel nur in diesem Tab.':'Vorabtest ohne Anmeldung. Melde dich anschließend an, um deine Einstellungen im Konto zu speichern.'}</p><div class="team-journal"><h3>Bestätigte Übergaben</h3><div id="team-journal-entries"></div></div>`;
  root.querySelectorAll('[data-key]').forEach(e=>e.value=keys.get(e.dataset.key)||'');
  renderJournal();renderBoards();
 }
 function renderJournal(){const e=$('team-journal-entries');if(e)e.innerHTML=journal.slice(0,12).map(j=>`<article><small>${esc(new Date(j.at*1000).toLocaleString())} · ${esc(label(j.role))}</small><p>${esc(j.summary)}</p><p class="muted">${esc((j.results||[]).map(r=>(r.ok?'✓ ':'Abgelehnt: ')+r.text).join(' · ')||'Bewusst gewartet')}</p></article>`).join('')||'<p class="empty">Noch kein bestätigter Teamzug. Nach einem Neustart erscheinen hier die letzten Übergaben dieser Epoche.</p>';}
 function renderBoards(){const e=$('pinboard-content');if(!e)return;e.innerHTML=`<div class="row"><button type="button" data-team="add-board">＋ Pinwand anlegen</button><button type="button" data-team="save">Pinwände speichern</button><button type="button" data-team="reload">Gespeicherten Stand laden</button><button type="button" data-team="export-boards">Pinwände exportieren</button></div><p class="muted">Für alle Spielweisen. Reihenfolge mit ↑ und ↓ ändern. Änderungen werden mit „Pinwände speichern“ dauerhaft im Konto gespeichert. Dein Team liest alle Karten bei jedem Zug neu. „An“ kann ein Teamname oder eine Rolle sein.</p><div class="pinboard-grid">${state().boards.map((b,i)=>`<article class="pinboard" data-board-id="${esc(b.id)}"><div class="row"><label>Titel der Pinwand<input data-board="title" maxlength="80" value="${esc(b.title)}"></label><button type="button" data-team="board-up" data-id="${esc(b.id)}" ${i===0?'disabled':''} aria-label="Pinwand nach oben">↑</button><button type="button" data-team="board-down" data-id="${esc(b.id)}" ${i===state().boards.length-1?'disabled':''} aria-label="Pinwand nach unten">↓</button><button type="button" class="danger" data-team="delete-board" data-id="${esc(b.id)}">Löschen</button></div>${b.world_id&&b.world_id!==world?.world_id?'<p class="muted">Aus einer früheren Epoche · Inhalte vor Verwendung prüfen.</p>':''}<div class="pinboard-notes">${b.notes.map((n,j)=>`<details class="pin-note" data-note-id="${esc(n.id)}" ${n.status!=='erledigt'?'open':''}><summary>${esc(n.title||'Neue Karte')} · ${esc(n.status)}</summary><label>Kartentitel<input data-note="title" maxlength="80" value="${esc(n.title)}"></label><label>Wissen, Ziel oder nächste Schritte<textarea data-note="text" rows="5" maxlength="3000">${esc(n.text)}</textarea></label><div class="row"><label>An<input data-note="to" maxlength="40" value="${esc(n.to)}" placeholder="Alle / Nova / Verwalter"></label><label>Status<select data-note="status">${['offen','aktiv','erledigt'].map(x=>`<option ${n.status===x?'selected':''}>${x}</option>`).join('')}</select></label></div><div class="row"><button type="button" data-team="note-up" data-id="${esc(n.id)}" ${j===0?'disabled':''}>↑ Karte</button><button type="button" data-team="note-down" data-id="${esc(n.id)}" ${j===b.notes.length-1?'disabled':''}>↓ Karte</button><button type="button" data-team="delete-note" data-id="${esc(n.id)}">Karte löschen</button></div></details>`).join('')}</div><button type="button" data-team="add-note" data-id="${esc(b.id)}" ${b.notes.length>=40?'disabled':''}>＋ Karte hinzufügen</button></article>`).join('')}</div><p id="pinboard-feedback" role="status">${dirty?'Ungespeicherte Änderungen.':'Gespeicherter Stand · Revision '+revision}</p>`;}
 async function sync(){
  if(syncing)return;syncing=true;
  try{
   const next=session?base+'|'+session.name:'';
   if(next!==owner){
    if(owner){keys.clear();probes.clear();data=null;dirty=false;journal=[];testAbort?.abort();}
    owner=next;revision=0;
    if(next){const w=await api('/api/workspace');if(w.state){data=w.state;dirty=false;}revision=w.revision;journal=w.journal;}render();
   }
   const target=session&&view&&!$('game').hidden?$('agent'):$('team-lobby-content');
   if(target&&$('team-workbench').parentElement!==target)target.prepend($('team-workbench'));
   $('team-lobby').hidden=target===$('agent');
  }catch(e){status('Teamdaten konnten nicht geladen werden: '+e.message,true);owner='';}
  finally{syncing=false;}
 }
 async function save(){
  if(!session)throw Error('Zum Speichern zuerst anmelden. Modelltests sind bereits ohne Anmeldung möglich.');
  if(agent)await stopAgent('Team gestoppt, damit Änderungen sicher übernommen werden.');
  const s=state();if(!s.models.every(m=>m.name.trim())||new Set(s.models.map(m=>m.name.trim().toLowerCase())).size!==s.models.length)throw Error('Jedes Modell braucht einen eigenen, eindeutigen Teamnamen.');
  if(!Number.isInteger(s.limit)||s.limit<1||s.limit>10000||!Number.isInteger(s.delay)||s.delay<15||s.delay>3600||!Number.isFinite(s.cost_limit)||s.cost_limit<0)throw Error('Prüfe Aufruflimit (1–10000), Rundenabstand (15–3600 s) und Kostenlimit (ab 0).');
  const w=await api('/api/workspace',{world_id:world.world_id,revision,state:s});data=w.state;revision=w.revision;journal=w.journal;dirty=false;render();status('Gespeichert · Revision '+revision+'. Ein gestopptes Team kann jetzt fortgesetzt werden.');$('pinboard-feedback').textContent='Dauerhaft gespeichert · Revision '+revision;
 }
 async function reload(force=false){if(dirty&&!force&&!confirm('Ungespeicherte Änderungen verwerfen und den gespeicherten Stand laden?'))return;if(!session)throw Error('Zuerst anmelden.');const w=await api('/api/workspace');data=w.state||defaults();revision=w.revision;journal=w.journal;dirty=false;render();}
 function friendly(e,m){if(e.name==='AbortError')return 'Abgebrochen · keine Spielaktion ausgeführt.';if(e.name==='TimeoutError')return 'Zeitüberschreitung. Modell zu langsam oder Speicher knapp; kleineres installiertes Modell wählen und erneut testen.';if(e instanceof TypeError)return m.provider==='ollama'?'Ollama vom Browser nicht erreichbar. Prüfe Adresse, laufendes Ollama, OLLAMA_ORIGINS und die lokale Netzwerkberechtigung. Details in der Anleitung.':'OpenRouter nicht erreichbar. Internetverbindung und Browser-Netzwerkfehler prüfen.';return e.message;}
 async function listModels(m){const local=m.provider==='ollama',r=await fetch(local?localURL(m.url)+'/api/tags':'https://openrouter.ai/api/v1/models',{signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Modellliste: HTTP '+r.status);const v=await r.json(),items=local?(v.models||[]).map(x=>({id:x.name,name:x.name+' · '+(x.size/1073741824).toFixed(1)+' GB'})):(v.data||[]).filter(x=>(x.architecture?.output_modalities||['text']).includes('text')).map(x=>({id:x.id,name:x.name+' · '+x.id}));catalogs.set(m.id,items);render();status(items.length+' Modelle gefunden. Wähle die exakte Modell-ID und teste sie.');}
 const pinSchema={type:'array',maxItems:4,items:{type:'object',additionalProperties:false,required:['board_id','note'],properties:{board_id:{type:'string'},note:{type:'object',additionalProperties:false,required:['id','title','text','to','status'],properties:{id:{type:'string',maxLength:80},title:{type:'string',maxLength:80},text:{type:'string',maxLength:3000},to:{type:'string',maxLength:40},status:{enum:['offen','aktiv','erledigt']}}}}}};
 const probeSchema={type:'object',additionalProperties:false,required:['aktionen','abfragen','begruendung','notiz','wecker_stunden','team_pins'],properties:{aktionen:{type:'array',maxItems:0,items:{type:'object'}},abfragen:{type:'array',maxItems:0,items:{type:'object'}},begruendung:{type:'string'},notiz:{type:'string'},wecker_stunden:{type:['number','null']},team_pins:{...pinSchema,maxItems:0}}};
 async function probe(m){
  const c=config(m),testedFingerprint=fingerprint(m);testAbort=new AbortController();const a={...c,limit:1,calls:0,tokens:0,cost:0,costLimit:0,controller:testAbort};
  probes.set(m.id,{message:'Prüfe Browserzugriff, Modellstart und strukturiertes JSON …'});render();
  try{const answer=await modelCall(a,[{role:'system',content:'Dies ist nur ein Verbindungstest. Keine Spielaktion. Antworte ausschließlich mit JSON gemäß Schema: '+JSON.stringify(probeSchema)},{role:'user',content:'Gib leere aktionen, abfragen und team_pins zurück und schreibe in begruendung: Verbindung funktioniert.'}],probeSchema);
   if(answer.aktionen.length||answer.abfragen.length||!Array.isArray(answer.team_pins)||answer.team_pins.length||typeof answer.begruendung!=='string')throw Error('Das Modell antwortet, hält aber das Testformat nicht ein. Anderes Modell wählen.');
   if(fingerprint(m)!==testedFingerprint)throw Error('Konfiguration während des Tests geändert. Erneut testen.');
   probes.set(m.id,{ok:true,fingerprint:testedFingerprint,message:`Bestanden · Browser → ${m.provider==='ollama'?'Ollama':'OpenRouter'} → ${m.model} · ${(a.latency/1000).toFixed(1)} s · ${a.tokens} Tokens${c.provider==='openrouter'?' · Kosten laut Anbieter: '+a.cost.toFixed(5)+' USD':''} · keine Spielaktionen.`});
  }catch(e){probes.set(m.id,{ok:false,message:friendly(e,m)});throw Error(m.name+': '+friendly(e,m));}finally{testAbort=null;render();}
 }
 async function testModels(ms){if(agent)throw Error('Vor Modelltests das laufende Team stoppen.');if(testing)throw Error('Ein Modelltest läuft bereits.');testing=true;try{for(const m of ms){await probe(m);}}finally{testing=false;render();}}
 async function rehearse(m){
  if(agent||testing)throw Error('Zuerst laufendes Team oder Modelltest stoppen.');if(!view||!session)throw Error('Die Spielprobe braucht dein Lagebild: erst anmelden und einen Spielplatz belegen. Der Verbindungstest funktioniert auch vorher.');if(!checked(m))throw Error('Zuerst den Verbindungstest bestehen.');
  const role=roles.find(r=>state().roles[r].model===m.id)||'verwalter',c=await api('/api/context',{rolle:role});c.schema=modelSchema(c.schema,c.view);c.schema.properties.team_pins={...pinSchema,maxItems:0};
  testAbort=new AbortController();testing=true;const a={...config(m),controller:testAbort,limit:2,calls:0,cost:0,tokens:0};
  $('team-workbench').querySelector('[data-team="cancel-test"]').hidden=false;
  status('Probe mit echtem Lagebild für '+label(role)+' · es werden keine Spielbefehle gesendet.');
  try{const r=state().roles[role],messages=[{role:'system',content:`Du bist ${m.name}, Rolle ${role}. Dies ist eine Spielprobe ohne Ausführung. soul.md: ${r.soul}\nrollen.md: ${r.instructions}\nRegeln: ${modelRules(c.text)}\nAntworte als JSON gemäß ${JSON.stringify(c.schema)}`},{role:'user',content:JSON.stringify({lagebild:compactView(c.view),pinwaende:state().boards})}];let answer=await modelCall(a,messages,c.schema);
   if(answer.abfragen.length){const answers=[];for(const q of answer.abfragen)answers.push({abfrage:q,antwort:await api('/api/tool',q)});messages.push({role:'assistant',content:JSON.stringify(answer)},{role:'user',content:'Lesende Werkzeugantworten: '+JSON.stringify(answers)+'. Entscheide jetzt ohne weitere Abfragen.'});answer=await modelCall(a,messages,c.schema);}
   $('agent-log').textContent=`SPIELPROBE · KEINE BEFEHLE AUSGEFÜHRT\n${m.name} · ${label(role)} · ${a.calls} Aufrufe · ${a.tokens} Tokens\n${answer.begruendung}\nVorschläge: ${JSON.stringify(answer.aktionen,null,2)}\nÜbergabe: ${answer.notiz||''}`;status('Spielprobe bestanden: Lagebild verarbeitet und gültiges Antwortformat. Die Ausführbarkeit einzelner Vorschläge prüft erst der Spielserver; es wurde nichts ausgeführt.');
  }finally{testing=false;testAbort=null;$('team-workbench').querySelector('[data-team="cancel-test"]').hidden=true;}
 }
 async function start(){
  if(agent)throw Error('Das Team läuft bereits.');if(testing)throw Error('Warte bis die Modelltests fertig sind.');if(!session||!view)throw Error('Zum Spielen zuerst anmelden und einen Spielplatz belegen. Die Tests brauchen keinen Spielplatz.');if(session.mode==='mensch')throw Error('Im Spielerprofil zuerst „Gemischt“ oder „Agent“ als Spielweise wählen. Deine Pinwände funktionieren auch als Mensch.');if(gameReadOnly())throw Error(gameReadOnly());if(dirty)throw Error('Änderungen zuerst speichern.');
  const s=state(),picked=roles.filter(r=>s.roles[r].model);if(!picked.length)throw Error('Mindestens einer Rolle ein Modell zuordnen.');if(session.mode==='agent'&&picked.length!==4)throw Error('Im Agentenspiel müssen alle vier Rollen besetzt sein. Ein Modell darf alle übernehmen.');
  const used=session.mode==='agent'?s.models:s.models.filter(m=>picked.some(r=>s.roles[r].model===m.id));for(const m of used){config(m);if(!checked(m))throw Error(m.name+': Bitte erst den Verbindungstest mit der aktuellen Modell-ID und dem aktuellen Schlüssel bestehen.');}
  const a={team:true,roles:picked,roleSettings:{},world_id:world.world_id,controller:new AbortController(),limit:s.limit,delay:s.delay,costLimit:s.cost_limit,calls:0,errors:0,tokens:0,cost:0,status:'Startet',latency:0};
  $('agent-status').textContent='Team startet · Steuerungsfreigabe wird angefordert …';
  // Council runs under a lease too, preventing a second tab from starting another crew.
  const lease=await api('/api/lease',{world_id:a.world_id,action:'start',roles:picked});a.lease=lease.lease;agent=a;$('agent-start').disabled=true;
  a.heartbeat=setInterval(async()=>{if(agent!==a)return;try{await api('/api/lease',{world_id:a.world_id,action:'heartbeat',lease:a.lease});}catch(e){await stopAgent(e.message);}},20000);
  try{if(session.mode==='agent')await council(a);if(agent!==a||a.controller.signal.aborted)return;status('Team aktiv · bestätigte Übergaben werden dauerhaft gespeichert.');void agentLoop(a);}catch(e){await stopAgent('Teamstart abgebrochen: '+e.message);throw e;}
 }
 async function council(a){
  const s=clone(state()),w=await api('/api/workspace');if(w.revision!==revision)throw Error('Team wurde anderswo geändert. Gespeicherten Stand laden.');
  const roster=s.models.map(m=>({id:m.id,name:m.name,model:m.model})),votes=[];
  const schema=clone(probeSchema);schema.required.push('rollenwahl');schema.properties.rollenwahl={type:'array',minItems:4,maxItems:4,items:{enum:roles}};
  for(const m of s.models){if(agent!==a)throw Error('Team gestoppt');a.currentRole=roles[0];a.roleSettings[a.currentRole]=config(m);const answer=await modelCall(a,[{role:'system',content:'Du bist '+m.name+'. Beratet als Team die Rollenverteilung. Sprich Kollegen mit Namen an. Gib in rollenwahl alle vier Rollen in deiner bevorzugten Reihenfolge an, jede genau einmal. Keine Aktionen, Abfragen oder Pins. Begründe deine Wahl anhand der Aufgaben und bisherigen Vorschläge. JSON-Schema: '+JSON.stringify(schema)},{role:'user',content:JSON.stringify({team:roster,rollen:s.roles,bisherige_vorschlaege:votes})}],schema);if(!Array.isArray(answer.rollenwahl)||new Set(answer.rollenwahl).size!==4||answer.rollenwahl.some(r=>!roles.includes(r))||answer.aktionen.length||answer.abfragen.length)throw Error(m.name+': Ungültige Rollenberatung; keine Spielaktion ausgeführt.');votes.push({id:m.id,name:m.name,bevorzugt:answer.rollenwahl,begruendung:String(answer.begruendung).slice(0,400)});}
  // Round-robin by model preference; a single model gets every role. Stable and auditable.
  const free=new Set(roles);while(free.size){for(const vote of votes){const r=vote.bevorzugt.find(x=>free.has(x));if(r){s.roles[r].model=vote.id;free.delete(r);}}}
  if(agent!==a||a.controller.signal.aborted)throw Error('Team gestoppt');
  let board=s.boards.find(b=>b.title==='Teamberatung');if(!board&&s.boards.length<20){board={id:uid(),title:'Teamberatung',world_id:a.world_id,notes:[]};s.boards.push(board);}if(board){const n={id:'rollenberatung',title:'Gemeinsam gewählte Rollen',text:votes.map(v=>`${v.name}: ${v.begruendung}`).join('\n')+'\nZuordnung: '+roles.map(r=>label(r)+' = '+roster.find(m=>m.id===s.roles[r].model).name).join(', '),to:'Alle',status:'aktiv'};const old=board.notes.findIndex(x=>x.id===n.id);if(old>=0)board.notes[old]=n;else if(board.notes.length<40)board.notes.push(n);}
  const saved=await api('/api/workspace',{world_id:a.world_id,revision,state:s});data=saved.state;revision=saved.revision;journal=saved.journal;render();
 }
 async function prepare(a,role,context){
  if(!a.team)return null;
  const w=await api('/api/workspace');if(dirty)throw Error('Ungespeicherte Änderungen: Team stoppen, speichern und fortsetzen.');if(!w.state)throw Error('Teamkonfiguration fehlt.');
  data=w.state;revision=w.revision;journal=w.journal;const r=data.roles[role],m=data.models.find(m=>m.id===r.model);if(!m||!checked(m))throw Error('Rollenmodell geändert oder nicht getestet. Bitte erneut testen und starten.');a.roleSettings[role]=config(m);a.teamTurn={revision,model_id:m.id};
  a.memorySnapshot=clone(data.boards);
  context.schema.properties.team_pins=pinSchema;
  context.schema.properties.abfragen.items.anyOf.push({type:'object',additionalProperties:false,required:['typ','board_id','ab'],properties:{typ:{enum:['pinwand_lesen']},board_id:{type:'string',enum:data.boards.map(b=>b.id)},ab:{type:'integer',minimum:0,maximum:40}}});
  let budget=12000;const boards=data.boards.map(b=>{const ordered=[...b.notes].sort((x,y)=>Number(y.to===m.name||y.to===role)-Number(x.to===m.name||x.to===role)||Number(x.status==='erledigt')-Number(y.status==='erledigt'));const notes=[];for(const n of ordered){const size=JSON.stringify(n).length;if(size<=budget){notes.push(n);budget-=size;}}return {...b,notes,karten_gesamt:b.notes.length,gekuerzt:notes.length<b.notes.length};});
  return {role,name:m.name,soul_md:r.soul,rollen_md:r.instructions,kollegen:roles.map(role=>({role,name:data.models.find(m=>m.id===data.roles[role].model)?.name||'Mensch'})),pinwaende:boards,gedaechtnis_hinweis:'Bei gekuerzt=true bleiben alle Karten gespeichert. Lies weitere Karten über abfragen: {typ:"pinwand_lesen",board_id,ab:0}. Eine Seite enthält vier Karten; nächste Seite ab=4 usw. Prüfe fehlende Ziele vor einer widersprechenden Entscheidung.',letzte_bestaetigte_zuege:journal.slice(0,8),world_id:a.world_id};
 }
 function readTool(a,q){if(q.typ!=='pinwand_lesen')return undefined;const b=a.memorySnapshot?.find(b=>b.id===q.board_id);if(!b)throw Error('Pinwand nicht vorhanden.');const start=Math.max(0,Number(q.ab)||0);return {id:b.id,title:b.title,world_id:b.world_id,notes:b.notes.slice(start,start+4),naechste_seite:start+4<b.notes.length?start+4:null};}
 function memoryPayload(a,answer){if(!a.team)return {};const pins=answer.team_pins||[];if(!Array.isArray(pins)||pins.length>4)throw Error('Höchstens vier Pinwandänderungen pro Zug.');return {team:{...a.teamTurn,summary:String(answer.notiz||answer.begruendung||'Bewusst gewartet').slice(0,1000),pins}};}
 function download(name,text,type='text/markdown'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function action(b){
  const s=state(),id=b.dataset.id,m=s.models.find(m=>m.id===id),board=s.boards.find(x=>x.id===(b.closest('[data-board-id]')?.dataset.boardId||id));
  switch(b.dataset.team){
   case 'add-model':if(s.models.length>=4)return;s.models.push({id:uid(),name:['Nova','Atlas','Vega','Lyra'].find(n=>!s.models.some(m=>m.name===n))||'Crew '+(s.models.length+1),provider:'ollama',url:'http://127.0.0.1:11434',model:''});changed();render();break;
   case 'remove-model':s.models=s.models.filter(x=>x.id!==id);for(const r of roles)if(s.roles[r].model===id)s.roles[r].model='';keys.delete(id);probes.delete(id);changed();render();break;
   case 'list-models':try{await listModels(m);}catch(e){throw Error(friendly(e,m));}break;
   case 'test':await testModels([m]);break;
   case 'rehearse':await rehearse(m);break;
   case 'test-all':if(!s.models.length)throw Error('Zuerst ein Modell hinzufügen.');await testModels(s.models);break;
   case 'cancel-test':testAbort?.abort();break;
   case 'save':await save();break;
   case 'reload':await reload();break;
   case 'start':await start();break;
   case 'stop':await stopAgent('Team gestoppt · Pinwände und bestätigte Übergaben bleiben erhalten.');status('Gestoppt. Zum Fortsetzen „Team starten / fortsetzen“ wählen.');break;
   case 'add-board':if(s.boards.length>=20)throw Error('Höchstens 20 Pinwände.');s.boards.push({id:uid(),title:'Neue Pinwand',world_id:world?.world_id||'',notes:[]});changed();renderBoards();break;
   case 'delete-board':if(!confirm('Pinwand „'+board.title+'“ mit allen Karten löschen? Erst Speichern übernimmt die Löschung.'))return;s.boards=s.boards.filter(x=>x!==board);changed();renderBoards();break;
   case 'board-up':case 'board-down':{const i=s.boards.indexOf(board),j=i+(b.dataset.team==='board-up'?-1:1);if(j>=0&&j<s.boards.length)[s.boards[i],s.boards[j]]=[s.boards[j],s.boards[i]];changed();renderBoards();break;}
   case 'add-note':if(board.notes.length>=40)throw Error('Höchstens 40 Karten je Pinwand.');board.notes.push({id:uid(),title:'Neues Ziel',text:'',to:'Alle',status:'offen'});changed();renderBoards();break;
   case 'delete-note':if(!confirm('Diese Karte löschen? Erst Speichern übernimmt die Löschung.'))return;board.notes=board.notes.filter(n=>n.id!==id);changed();renderBoards();break;
   case 'note-up':case 'note-down':{const i=board.notes.findIndex(n=>n.id===id),j=i+(b.dataset.team==='note-up'?-1:1);if(j>=0&&j<board.notes.length)[board.notes[i],board.notes[j]]=[board.notes[j],board.notes[i]];changed();renderBoards();break;}
   case 'export-role':download(b.dataset.file==='soul'?'soul.md':'rollen.md',s.roles[id][b.dataset.file]);break;
   case 'export-boards':download('pinwaende.json',JSON.stringify(s.boards,null,2),'application/json');break;
  }
 }
 function input(e){const el=e.target,s=state();if(el.dataset.key){keys.set(el.dataset.key,el.value.trim());probes.delete(el.dataset.key);const p=document.querySelector(`[data-probe-result="${el.dataset.key}"]`);if(p)p.textContent='Schlüssel geändert · erneut testen';return;}
  const mid=el.closest('[data-model-id]')?.dataset.modelId,rid=el.closest('[data-role-id]')?.dataset.roleId,bid=el.closest('[data-board-id]')?.dataset.boardId,nid=el.closest('[data-note-id]')?.dataset.noteId;
  if(el.dataset.model){s.models.find(m=>m.id===mid)[el.dataset.model]=el.value;probes.delete(mid);const p=document.querySelector(`[data-probe-result="${mid}"]`);if(p){p.textContent='Konfiguration geändert · erneut testen';p.classList.remove('good');}changed();if(el.dataset.model==='provider'){catalogs.delete(mid);s.models.find(m=>m.id===mid).model='';render();}}
  else if(el.dataset.catalog){s.models.find(m=>m.id===el.dataset.catalog).model=el.value;probes.delete(el.dataset.catalog);changed();render();}
  else if(el.dataset.role){s.roles[rid][el.dataset.role]=el.value;changed();}
  else if(el.dataset.limit){s[el.dataset.limit]=Number(el.value);changed();}
  else if(el.dataset.note){s.boards.find(b=>b.id===bid).notes.find(n=>n.id===nid)[el.dataset.note]=el.value;changed();$('pinboard-feedback').textContent='Ungespeicherte Änderungen.';}
  else if(el.dataset.board){s.boards.find(b=>b.id===bid)[el.dataset.board]=el.value;changed();$('pinboard-feedback').textContent='Ungespeicherte Änderungen.';}
 }
 document.addEventListener('input',input);
 document.addEventListener('change',async e=>{const id=e.target.dataset.importRole;if(!id)return;try{const f=e.target.files[0];if(!f)return;if(f.size>12000)throw Error('Markdown-Datei zu groß.');const target=document.querySelector(`[data-import-target="${id}"]`).value,text=await f.text();if(text.length>(target==='soul'?2000:3000))throw Error('Text überschreitet das Rollenlimit.');state().roles[id][target]=text;changed();render();}catch(err){show(err.message,true);}});
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-team]');if(!b||b.disabled)return;if(b.dataset.team==='cancel-test'){testAbort?.abort();return;}if(busy)return;busy=true;b.disabled=true;try{await action(b);}catch(err){status(err.message,true);show(err.message,true);if($('pinboard-feedback'))$('pinboard-feedback').textContent=err.message;}finally{busy=false;if(b.isConnected)b.disabled=false;}});
 window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
 window.addEventListener('DOMContentLoaded',()=>{
  $('agent-settings').hidden=true;const intro=$('agent').querySelector('h2');if(intro)intro.hidden=true;
  render();void sync();
 });
 function validateAnswer(value,schema,path='Antwort'){
  if(schema.anyOf){if(!schema.anyOf.some(s=>{try{validateAnswer(value,s,path);return true;}catch{return false;}}))throw Error(path+': keine erlaubte Variante.');return;}
  if(schema.enum&&!schema.enum.some(x=>JSON.stringify(x)===JSON.stringify(value)))throw Error(path+': unerlaubter Wert.');
  const types=Array.isArray(schema.type)?schema.type:[schema.type];const matches=t=>t===undefined||t==='null'&&value===null||t==='array'&&Array.isArray(value)||t==='object'&&value!==null&&typeof value==='object'&&!Array.isArray(value)||t==='integer'&&Number.isInteger(value)||t==='number'&&typeof value==='number'&&Number.isFinite(value)||['string','boolean'].includes(t)&&typeof value===t;
  if(!types.some(matches))throw Error(path+': falscher Datentyp.');
  if(typeof value==='string'&&schema.maxLength&&[...value].length>schema.maxLength)throw Error(path+': Text zu lang.');
  if(typeof value==='number'&&(schema.minimum!==undefined&&value<schema.minimum||schema.maximum!==undefined&&value>schema.maximum))throw Error(path+': Zahl außerhalb des erlaubten Bereichs.');
  if(Array.isArray(value)){if(value.length>(schema.maxItems??Infinity)||value.length<(schema.minItems??0))throw Error(path+': falsche Anzahl Einträge.');if(schema.items)value.forEach((v,i)=>validateAnswer(v,schema.items,path+'['+i+']'));}
  else if(value&&typeof value==='object'){for(const k of schema.required||[])if(!(k in value))throw Error(path+': Pflichtfeld '+k+' fehlt.');for(const [k,v] of Object.entries(value)){if(schema.properties?.[k])validateAnswer(v,schema.properties[k],path+'.'+k);else if(schema.additionalProperties===false)throw Error(path+': unbekanntes Feld '+k);}}
 }
 return {sync,prepare,memoryPayload,readTool,localURL,validateAnswer,afterTurn:async a=>{if(!a.team)return;const w=await api('/api/workspace');if(!dirty){data=w.state;revision=w.revision;renderBoards();}journal=w.journal;renderJournal();},inspect:()=>({revision,dirty,models:state().models.length})};
})();
