'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let key='',state=null,busy=false,timer,prepared=null;
function message(s,error=false){$('message').textContent=s;$('message').hidden=false;$('message').classList.toggle('error',error);clearTimeout(timer);timer=setTimeout(()=>$('message').hidden=true,8000);}
async function api(path,body){const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'X-Sternenepoche-Admin':key,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(20000)});const v=await r.json();if(!r.ok)throw Error(v.error);return v;}
const table=(head,rows)=>`<table><thead><tr>${head.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
async function refreshBase(){if(busy)return;busy=true;try{state=await api('/api/admin/status');const w=state.lobby;$('status').textContent=state.storage_error|| (w.paused?'Welt pausiert':'Server läuft');$('summary').innerHTML=[['Tag',Math.floor(w.sekunden/86400)+1],['Freie Plätze',w.freie_plaetze+'/20'],['Flotten',state.flotten],['Ereignisse',state.ereignisse],['Tempo',w.tempo+'×'],['Uptime',Math.floor(state.uptime_s/60)+' Min.'],['Datenbank',(state.db_bytes/1048576).toFixed(1)+' MiB'],['Invarianten',state.invariant_errors.length?'FEHLER':'OK']].map(([k,v])=>`<div class="stat"><strong>${esc(v)}</strong><span>${esc(k)}</span></div>`).join('');
 if(!document.activeElement?.closest('#settings')){$('tempo').value=w.tempo;$('epoch-days').value=state.epoche_tage;$('bot-period').value=state.bot_period_secs;$('paused').checked=w.paused;$('bots-enabled').checked=state.bots_enabled;$('maintenance').value=w.maintenance||'';}
 $('world-hash').textContent='Welt '+w.world_id+' · Zustand '+state.world_hash;
 $('accounts').innerHTML=table(['Konto','Name','Spieler','Modus','Status',''],state.accounts.map(a=>[a.id,esc(a.name),a.spieler??'Zuschauer',esc(a.mode),a.banned?'Gesperrt':'Aktiv',`<button data-account="${a.id}" data-banned="${!a.banned}" class="secondary">${a.banned?'Entsperren':'Sperren'}</button>`]));
 $('bots').innerHTML=table(['Nr.','Name','Strategie','Aktionen','Abgelehnt','Nächster Zug (Spielsek.)','Stufe / Punkte'],state.bots.map(b=>[b.spieler,esc(b.name),esc(b.typ),b.aktionen,b.abgelehnt,b.naechster,`${b.stufe} / ${b.punkte}`]));
 $('bot-health').textContent=`${state.bot_actions} ausgeführte Aktionen · ${state.bot_rejected} abgelehnte Aktionen. Bei hohen Ablehnungszahlen Voraussetzungen und Strategie prüfen.`;
 $('agents').innerHTML=table(['Spieler','Freigabe','Status','Aufrufe','Fehler','Tokens','Antwortzeit',''],state.agents.map(a=>[a.spieler,a.active?'Aktiv':'Gestoppt',esc(a.stats.status),a.stats.calls,a.stats.errors,a.stats.tokens,a.stats.latency_ms+' ms',`<button data-stop="${a.spieler}" class="secondary">Stoppen</button>`]));
 $('confirm').placeholder='RESET '+w.world_id;
 }catch(e){$('status').textContent='Verbindung unterbrochen';message(e.message,true);}finally{busy=false;}}
async function action(v){const result=await api('/api/admin/action',{world_id:state.lobby.world_id,...v});message(result.backup?'Backup: '+result.backup:'Änderung gespeichert');await refresh();return result;}
async function refresh(){await refreshBase();if(typeof renderMonitoring==='function')renderMonitoring();}
function guard(fn){return async e=>{if(e?.type==='submit')e.preventDefault();const b=e?.type==='submit'?e.submitter:e?.currentTarget;if(b?.disabled)return;if(b)b.disabled=true;try{await fn(e);}catch(e){message(e.message,true);}finally{if(b)b.disabled=b.id==='reset-submit'&&!prepared;}};}
$('settings').addEventListener('submit',guard(async()=>{await action({action:'settings',tempo:Number($('tempo').value),epoche_tage:Number($('epoch-days').value),bot_period_secs:Number($('bot-period').value),paused:$('paused').checked,bots_enabled:$('bots-enabled').checked,maintenance:$('maintenance').value});}));
$('bot-edit').addEventListener('submit',guard(async e=>{const f=e.target.elements;await action({action:'bot',spieler:Number(f.spieler.value),typ:f.typ.value});}));
$('player-edit').addEventListener('submit',guard(async e=>{const f=e.target.elements;await action({action:'player_edit',spieler:Number(f.spieler.value),...(f.credits.value===''?{}:{credits:Number(f.credits.value)}),...(f.menge.value===''?{}:{bestand:{[f.gut.value]:Number(f.menge.value)}})});}));
$('reset').addEventListener('submit',guard(async()=>{if(!prepared||prepared.text!==$('rule-profile').value||prepared.world!==state.lobby.world_id)throw Error('Regelprofil und aktuelle Welt zuerst prüfen');await action({action:'reset',rules:prepared.text,confirm:$('confirm').value,...($('seed').value===''?{}:{seed:Number($('seed').value)})});$('confirm').value='';invalidateProfile();}));
$('inspect').addEventListener('submit',guard(async e=>{const v=await read({action:'inspect',spieler:Number(e.target.elements.spieler.value)});$('inspection').innerHTML=cards([{name:v.name,volk:v.volk,stufe:v.stufe,credits:v.credits,forschung:v.forschung,flotten:v.flotten},...v.planeten]);}));
$('backup').onclick=guard(async()=>{await action({action:'backup'});});$('refresh').onclick=refresh;
document.addEventListener('click',guard(async e=>{const b=e.target.closest('[data-account],[data-stop]');if(!b)return;if(b.dataset.account)await action({action:'account',id:Number(b.dataset.account),banned:b.dataset.banned==='true'});else await action({action:'stop_agent',spieler:Number(b.dataset.stop)});}));
(async()=>{try{const b=await api('/api/admin/bootstrap');key=b.key;$('game-link').href=b.game_url;await refresh();setInterval(refresh,10000);}catch(e){message(e.message,true);}})();
